#!/usr/bin/perl
$num = int(1 + rand 100);
#print "num is $num \n"%;
while (1) {
  print "Enter a number between 1 and 100\n";
  chomp (my $guess = <STDIN>);
  if ($guess =~ /-?\d+\.?\d*/) { 
    $guess - $num ? $guess < $num ?
        print "Too low\n" :
        print "Too high\n"
        : last
  } else {
    last if ($guess eq "exit" || $guess eq "quit" || !$guess);
  }
}
